content/jp/docs/guides/_index.md

chore: test github actions

---

config.toml

Fix title typo

---

content/en/community/_index.md
content/jp/community/_index.md
content/ko/community/_index.md

Migrate spaceone links to cloudforet

Update new links to cloudforet-io

---

config.toml
content/en/_index.html
content/en/docs/developers/architecture/deployment/_index.md
content/en/docs/developers/contribute/documentation/style_guide.md
content/en/docs/guides/info/notice.md
content/en/docs/introduction/release_notes/release_note_list/v1.8.2.md
content/en/docs/introduction/release_notes/release_note_list/v1.9.0.md
content/jp/_index.html
content/jp/docs/developers/architecture/deployment/_index.md
content/jp/docs/developers/contribute/documentation/style_guide.md
content/jp/docs/guides/info/notice.md
content/jp/docs/introduction/release_notes/release_note_list/v1.8.2.md
content/jp/docs/introduction/release_notes/release_note_list/v1.9.0.md
content/ko/_index.html
content/ko/docs/developers/architecture/deployment/_index.md
content/ko/docs/developers/contribute/document/style_guide.md
content/ko/docs/guides/info/notice.md
content/ko/docs/introduction/release_notes/release_note_list/v1.8.2.md
content/ko/docs/introduction/release_notes/release_note_list/v1.9.0.md
layouts/partials/head.html
layouts/robots.txt

fix: change 'spaceone.org' to 'cloudforet.io'

---

layouts/partials/footer.html

Add LinuxFoundation license

---

content/en/community/_index.md
content/jp/community/_index.md
content/ko/community/_index.md

Change discussion url

---

content/ko/docs/introduction/release_notes/_index.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.1.md

- Add 1.10.1 Release Note (KR)

Add 1.10.1 Release Note (KR)

---

content/ko/docs/introduction/release_notes/release_note_list/v1.10.1.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.2.md

- Change 1.10.1 Release Note
- Add 1.10.2 Release Note (KR)

Add 1.10.2 Release Note (KR)

---

content/ko/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.3.md

- Add 1.10.3 Release Note (KR)
- Change 1.10.2 Release Note

Add 1.10.3 Release Note (KR)

---

content/en/docs/introduction/release_notes/_index.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.1.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.3.md
content/jp/docs/introduction/release_notes/_index.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.1.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.3.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.2.md

- Add 1.10.1 release note (EN)
- Add 1.10.2 release note (EN)
- Add 1.10.3 release note (EN)

Add Release Notes

---

content/en/docs/introduction/release_notes/_index.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.3.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/jp/docs/introduction/release_notes/_index.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.3.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/ko/docs/introduction/release_notes/_index.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.2.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.3.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.4.md

- Add 1.10.4 release note
- Fix wrong release dates

Add Release Note

---

content/en/docs/introduction/release_notes/_index.md
content/en/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/jp/docs/introduction/release_notes/_index.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/ko/docs/introduction/release_notes/_index.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.4.md

- change release date in 1.10.4 release note

doc: change 1.10.4 release note

---

content/en/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/jp/docs/introduction/release_notes/release_note_list/v1.10.4.md
content/ko/docs/introduction/release_notes/release_note_list/v1.10.4.md

Fix release note

---

content/en/docs/developers/design_system/_index.md
content/ko/docs/developers/design_system/_index.md

Fix english translation of the Design System Documentation

fix: design system document

---

content/en/docs/guides/plugins/asset-inventory-collector.md
content/jp/docs/guides/plugins/asset-inventory-collector.md

- modify Azure Collector link and remove deprecated collector link(en, jp)
- same with this #61

Modify Azure Collector link and remove deprecated collector link(en, jp)

---

README.md

Updated readme's git clone command to allow cloning of private repositories

fix: clone command in readme

---

content/en/projects/_index.md
content/jp/projects/_index.md
content/ko/projects/_index.md
layouts/projects/baseof.html
layouts/projects/list.html

Update Project skeleton

---

content/en/projects/_index.md
content/jp/projects/_index.md
content/ko/projects/_index.md

Add project proposal template

---

layouts/projects/list.html

Update header image

---

deploy/helm/Chart.yaml
deploy/helm/templates/ingress.yaml
deploy/helm/values.yaml

- docs helm chart has been updated
- update apiVersion
- replaced ingressClassName annotation
- update rules

helm: update ingress apiVersion

---

deploy/helm/Chart.yaml
deploy/helm/templates/ingress.yaml

- adding if condition in ingress

helm: add if condition in ingress

---

deploy/helm/Chart.yaml
deploy/helm/templates/deployment.yaml

- Support custom serviceAccount

helm: update chart to support custom SA

---

content/en/docs/developers/_index.md
content/en/docs/developers/architecture/_index.md
content/en/docs/developers/architecture/deployment/_index.md
content/en/docs/developers/architecture/microservice_framework/_index.md

Migrate from SpaceONE to Cloudforet

---

content/en/docs/concepts/identity/rbac/_index.md
content/en/docs/concepts/identity/rbac/understanding-policy.md
content/en/docs/concepts/identity/rbac/understanding-role.md
content/en/docs/introduction/key_differentiators/_index.md
content/en/docs/introduction/overview/_index.md

- Updated some sentences in below documentations.
- Introduction -> Overview
- Introduction -> Key Differentiators
- Concepts -> Identity -> Role Based Access Control
- Concepts -> Identity -> Role Based Access Control -> Understanding Policy
- Concepts -> Identity -> Role Based Access Control -> Understanding Role
- x

chore(docs): Clarify some sentences

---

content/en/docs/guides/getting-started/_index.md

Signed-off-by: Minho Kim <mino@megazone.com>
- fix typo in guide > getting-started
- `**Start cost analysis**` -> `Start **cost analysis**`

Fix typo in guide > getting-started

---

content/en/docs/setup_operation/install_guide/_index.md
content/en/docs/setup_operation/install_guide_on_premise/_index.md

Added a new installation guide for on-premises environments.

feat: add install guide for on_prem env

---

content/en/docs/setup_operation/install_guide_on_premise/_index.md

docs: fix helm repo update command

---

content/en/docs/setup_operation/install_guide_on_premise/_index.md

Edit comment to be more specific

docs: fix comment

---

content/en/docs/setup_operation/advanced_configuration/_index.md
content/en/docs/setup_operation/advanced_installation/_index.md
content/en/docs/setup_operation/install_guide/_index.md
content/en/docs/setup_operation/operation/_index.md
content/en/docs/setup_operation/quick_install/_index.md

- Clarified some sentences under "Setup & Operation".

chore(docs): Clarify some sentences in Setup & Configuration

---

content/en/docs/setup_operation/install_guide_on_premise/_index.md

Add example value links in on-prem installation guide.

docs: link to examples in on-prem guide

---

content/en/docs/setup_operation/quick_install/_index.md

Fix quick install type

---

content/en/docs/setup_operation/quick_install/_index.md

Add 'versions are subject to change' guide to quick install guide.

docs: add 'versions are subject to change'

---

assets/scss/_community.scss
content/en/community/_index.md
content/jp/community/_index.md

* translate content to English
* fix minor styles for responsive

feat(community): translate content to English

---

assets/scss/_box.scss
assets/scss/_breadcrumb.scss
assets/scss/_community.scss
assets/scss/_content.scss
assets/scss/_footer.scss
assets/scss/_functions.scss
assets/scss/_home.scss
assets/scss/_main-container.scss
assets/scss/_nav.scss
assets/scss/_navbar.scss
assets/scss/_pageinfo.scss
assets/scss/_projects.scss
assets/scss/_search.scss
assets/scss/_section-index.scss
assets/scss/_sidebar-toc.scss
assets/scss/_sidebar-tree.scss
assets/scss/_variables_project.scss

feat: add color set

---

config.toml

Create new branch (release-1.11.0)
Need DNS for old release page

Update relase branch

---

content/en/docs/setup_operation/quick_install/_index.md
content/ja/docs/setup_operation/quick_install/_index.md

Fix quick install content

---

content/en/docs/setup_operation/quick_install/_index.md

Migrate SpaceONE to Cloudforet

Migrate SpaceONE to Cloudforet

---

Dockerfile

* Update docker base image version due to security issues

ci: update base image version

---

content/en/community/_index.md
content/ja/community/_index.md
content/ko/community/_index.md
layouts/partials/footer.html

Rename community repo to cloudforet.
- [x ] Fix Content

Change community project to cloudforet

---

layouts/partials/footer.html

SSIA
[Quest - 205](https://pyengine.atlassian.net/browse/QUEST-205)

fix: edit footer link & remove youtube link and icon

---

content/en/docs/developers/plugins/_index.md
content/en/docs/developers/plugins/about_plugin/_index.md

Update plugin development

---

content/ko/docs/setup_operation/configuration/set_http_proxy.md
content/ko/docs/setup_operation/configuration/set_k8s_imagepullsecrets.md

improve: update indent and sentence

---

content/en/docs/setup_operation/quick_install/_index.md

- Update docs version to 1.11.0

fix: update spaceone/docs version

---

content/en/docs/setup_operation/configuration/set_http_proxy.md

fix: delete dot in title

---

content/en/docs/setup_operation/configuration/set_http_proxy.md
content/en/docs/setup_operation/configuration/set_k8s_imagepullsecrets.md
content/ko/docs/setup_operation/configuration/set_http_proxy.md
content/ko/docs/setup_operation/configuration/set_k8s_imagepullsecrets.md

fix: update contents after review

---

content/ko/docs/setup_operation/configuration/change_k8s_namespace.md
content/ko/docs/setup_operation/install_guide_on_premise/_index.md

fix: change configuration link path

fix: change config link path

---

content/en/docs/setup_operation/quick_install/_index.md

I forgot to take out all the comments. Sorry for the inconvenience.

took out extra comments

---

content/en/docs/setup_operation/configuration/set_plugin_certificate.md

Change img path in plugin certificate settings

---

content/en/docs/setup_operation/install_guide_on_premise/_index.md
content/ko/docs/setup_operation/install_guide_on_premise/_index.md

feat: change wrong links

---

content/en/docs/setup_operation/configuration/support_private_image_registry.md
content/ko/docs/setup_operation/configuration/support_private_image_registry.md

Add description for docker running

feat: description of docker run command

---

content/en/docs/setup_operation/monitoring/_index.md
content/en/docs/setup_operation/quick_install/_index.md

- [x] Fix Content
remove monitoring and change name to getting started

feat: remove monitoring and change name

---

content/ko/docs/guides/plugins/cost-explorer-data-source.md

- Update supported plugin list in docs
- aws-cost-expolorer
- azure-cost-mangement

Update supported plugin list in docs

---

content/en/docs/setup_operation/configuration/advanced_configuration/_index.md
content/en/docs/setup_operation/configuration/change_k8s_namespace.md
content/en/docs/setup_operation/configuration/set_http_proxy.md
content/en/docs/setup_operation/configuration/set_k8s_imagepullsecrets.md
content/en/docs/setup_operation/configuration/set_plugin_certificate.md

feat: change title convention.

feat: change title convention.

---

content/en/docs/setup_operation/configuration/set_http_proxy.md
content/ko/docs/setup_operation/configuration/set_http_proxy.md

Depending on the installation environment, the default local domain in kubernetes cluster may differ.
So User would change default local domain

feat: update README.md of set_http_proxy

---

content/en/docs/setup_operation/quick_install/_index.md

Updated the Quick Install guide:
1. Added some additional guidance for EC2 users in terms of IP address.
2. Added additional information about getting pod names.

updated Quick Install guide based on feedback

---

content/en/docs/setup_operation/quick_install/_index.md

Found minor parts that need a bit of details.

found additional parts that need more information - updated

---

content/en/docs/setup_operation/configuration/create_secret_by_exist_cert.md
content/en/docs/setup_operation/installation/on_premise.md
content/ko/docs/setup_operation/configuration/change_k8s_namespace.md
content/ko/docs/setup_operation/configuration/create_secret_by_exist_cert.md
content/ko/docs/setup_operation/installation/on_premise.md

feat: update on-premise and secret

feat: update on-premise and secret

---

content/en/docs/guides/cost-explorer/_index.md
content/en/docs/guides/cost-explorer/cost-analysis.md
content/ja/docs/guides/cost-explorer/_index.md
content/ja/docs/guides/cost-explorer/cost-analysis.md
content/ko/docs/guides/cost-explorer/_index.md
content/ko/docs/guides/cost-explorer/cost-analysis.md

- image issues 
- a few contents updated

image issue fixed & contents updated

---

content/en/docs/guides/cost-explorer/cost-analysis.md
content/ja/docs/guides/cost-explorer/cost-analysis.md
content/ko/docs/guides/cost-explorer/cost-analysis.md

image issue fixed

---

content/en/docs/setup_operation/installation/on_premise.md
content/ko/docs/setup_operation/installation/on_premise.md

Change spaceone-initializer.yaml file contents for release-1.12

feat: change guide for spaceone initializer

---

content/en/docs/setup_operation/installation/on_premise.md
content/ko/docs/setup_operation/installation/on_premise.md

feat: modify pod list recently

---

content/en/docs/setup_operation/quick_install/_index.md

Updating the link for discussion channel and adding warning before the kubectl logs command in quick_installation

---

content/en/docs/setup_operation/quick_install/_index.md

Added an error correction related to setting docker as the driver for the minikube. 
This is the most common error error which is faced a lot of users which needs to be addressed.

Briefing the installation procedure

---

content/en/docs/setup_operation/installation/on_premise.md

Adding the correct initializer.yaml in on_premise installation and correct Helm version

---

content/en/docs/setup_operation/quick_install/_index.md

Fix spaceone chart version. 1.12.11 has a bug for default value.

Fix helm chart version

---

content/en/docs/developers/api_sdk/_index.md

Add API Document link

---

content/en/docs/developers/contribute/_index.md
content/en/docs/developers/contribute/documentation/_index.md
content/en/docs/developers/contribute/documentation/content_guide.md
content/en/docs/developers/contribute/documentation/style_guide.md

Change SpaceONE to Cloudforet

---

content/ko/docs/guides/cost-explorer/quick-start.md

- add quick-start guide for cost-explorer

Add quick-start guide for cost-explorer
